name: 'Auto rebase'
description: 'Automatically rebases pull requests that are out-of-date.'

inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true
  opt_out:
    description: Change to opt-out mode, Auto rebase will rebase PRs unless they are labeled with the opt-out label.

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'arrow-up-right'
  color: 'green'
